USE maisoneauor;

INSERT INTO products (name, description, price, image, category) VALUES
('Ultimate K.O.', "UFC Ultimate K.O. est un parfum qui capture la puissance, la précision et le charisme audacieux. Il s’ouvre avec un mélange vibrant de cardamome, de lavande et d’orange, offrant une montée de fraîcheur épicée comme le calme avant un combat. Le cœur mélange la sauge sclarée, la fleur d’oranger et le caramel, ajoutant une chaleur herbacée et une douce profondeur - la force rencontre la stratégie. Le fond boisé ambré laisse un sillage riche et masculin qui dure, faisant écho à l’impact d’un knockout. Un parfum audacieux et raffiné pour ceux qui revendiquent la victoire avec confiance.", 50.00, '/assets/img/products/ultimate_ko.PNG', 6),
('Scorpio Rouge', "Rouge by Scorpio est un parfum pour hommes qui a été lancé en 1989. Le parfum s'ouvre sur une combinaison fraîche de bergamote et de notes d'agrumes vives qui apportent un début énergique et optimiste. Cette première bouffée est classique et intemporelle, rappelant les parfums masculins d'une époque où l'élégance et l'assurance allaient de pair. La lavande aromatique apparaît au cœur de la composition, complétée par des notes d'herbes fraîches et une touche rafraîchissante de menthe. Ces ingrédients créent un sentiment de pureté et d'acuité subtile qui semble naturel et charismatique. Le cœur aromatique se marie magnifiquement avec la fraîcheur du début, faisant évoluer le parfum vers un final harmonieux. La base du parfum repose sur des notes boisées profondes, un bois de santal crémeux et un patchouli sombre et doux comme la terre. Cette combinaison confère au parfum masculinité, chaleur et longévité. Rouge by Scorpio est un classique qui continue de séduire par sa construction simple mais réfléchie - un parfum pour l'homme qui sait que le vrai style n'est pas soumis au temps.", 15.00, '/assets/img/products/scorpio_rouge.PNG', 6),
('MAN MAN Mercedes', "Mercedes-Benz Man, la manifestation authentique des valeurs d'une marque mythique - c'est la légende de Mercedes-Benz dans un flacon. Le maître parfumeur Olivier Cresp présente ce parfum intemporel et sophistiqué. Le cœur aromatique intense de feuille de cèdre et de géranium incarne l'élégance. Les notes fruitées et subtilement modernes de la poire se mêlent aux graines d'ambrette pour un résultat frais et contemporain. Le sillage profond et boisé est libéré par le bois de rose et la mousse de chêne. Une composition luxueuse pour une identité clairement définie.", 45.00, '/assets/img/products/man_man_mercedes.PNG', 6),
('Encens d\'Hiver', "Le rêve retrouvé des paysages immaculés du Grand Nord. Au loin, s’échappent des forêts des volutes réconfortantes de labdanum aux notes d’encens. Le thé parfumé et brûlant se mêle à l’odeur du feu de bois. Les notes boisées de cèdre survolent les étendues enneigées à perte de vue.", 105.00, '/assets/img/products/ences_hiver.PNG', 3),
('Diffuseur à bâtonnets Cedar Wood', "Cedar Wood | Les arômes typiques d’une herboristerie traditionnelle, floraux, boisés et sucrés, s’entremêlent dans un ensemble de senteurs modernes et tendance. Acidulé et floral, découvrez son fond boisé subtilement sucré grâce à une touche de canne à sucre.", 20.00, '/assets/img/products/diffuseur_cedar_wood.PNG', 3),
('Precious Amber Fragrance Sticks', "Laissez-vous porter par la senteur douce et suave de nos bâtonnets parfumés Precious Amber composés à partir d’un mélange d’ylang-ylang, de patchouli, de vétiver et d’ambre intense.", 50.00, '/assets/img/products/precious_amber_fragrance_sticks.PNG', 3),
('Musc Tahara – El Nabil', "Découvrez ce parfum frais aux notes de coton, de musc blanc, de fleurs de lotus blanc et de jasmin. Utilisé par de nombreuses femmes à travers le monde dans un processus de nettoyage intime et corporel, ce parfum doux et sucré promet de respecter les parties les plus sensibles de votre corps tout en offrant une expérience olfactive incomparable.", 11.00, '/assets/img/products/el_nabil.PNG', 5),
('MUSK TAHARA ROYAL', "Plongez dans un rêve envoûtant avec cette huile parfumée mixte, une fragrance florale qui célèbre la grâce et la douceur. Elle dévoile la fraîcheur d’une tige de rose et la délicatesse du lotus blanc, évoquant un jardin lumineux baigné de lumière. Les accords raffinés de miel et de vanille se mêlent à un cœur floral somptueux dominé par la rose Taif, offrant une chaleur enveloppante et une touche élégante. Un souffle musqué vient parfaire cette harmonie. Enfin, le musc poudré laisse un sillage tendre et addictif, enveloppant la peau d’une aura douce et sensuelle. Cette huile est une invitation à la légèreté et au raffinement.", 50.00, '/assets/img/products/musc_tahara_royal.PNG', 5),
('Musc Tahara - Caraïbe Coco', "Le Musc Tahara Caraïbe Coco de Gris Montaigne, en flacon de 12 ml, est un parfum envoûtant alliant des notes exotiques de noix de coco, vanille et musc tahara. Sa fragrance fraîche et sensuelle, à la fois gourmande et florale, évoque la féminité et l'évasion vers des plages tropicales.", 23.00, '/assets/img/products/musc_tahara_caraibe_coco.PNG', 5),
('Brume Parfumée Vanille Bourbon', "Une sensation de Nature avec cette brume parfumée corps & cheveux. Senteur : Vanille Bourbon. Zone d'application : Corps et cheveux. Formule fondante à 98% d'origine naturelle. Hydrate et parfume délicatement la peau. Enrichie en beurre de karité. La senteur : Yves Rocher a choisi une Vanille Bourbon cultivée selon la tradition de l’île Bourbon. De la famille des Orchidées, son parfum laisse sur la peau un voile de sensualité satinée, comme une caresse enivrante. La senteur s’ouvre sur une note lumineuse puis dévoile sa personnalité envoûtante.", 20.00, '/assets/img/products/brume_vanille_bourbon.PNG', 4),
('Velvet Oudh Home Perfume', "Enveloppez vos sens de l’accord aromatique de ce parfum d’intérieur raffiné, formulé à partir de l’élégance de l’oud, de la rose et du safran.", 40.00, '/assets/img/products/velvet_oudh_home_perfume.PNG', 4),
('Spray parfum d\'intérieur Thé Marocain', "Le spray parfum d'intérieur Thé Marocain de Tour de Grasse capture la subtilité enivrante et l'élégance apaisante du thé à la menthe marocain. Cette fragrance captivante révèle la fraîcheur vivifiante et la douceur délicate qui caractérisent ce breuvage emblématique. Tel un moment de détente olfactif, ce parfum vous transporte vers une oasis de tranquillité où les arômes envoûtantes du thé fraîchement infusé à la menthe s'entremêlent dans l'air.", 25.00, '/assets/img/products/parfum_interieur_the_marocain.PNG', 4),
('Spray Coiffant Texturant', "Ce Spray Coiffant donne immédiatement plus de texture à vos cheveux, pour plus de volume tout en ayant un effet naturel. Sa fixation est légère et le produit se rince facilement à l’eau.", 11.00, '/assets/img/products/spary_coiffant_texturant.PNG', 1),
('Booster capillaire anti-chute', "Dès 2 mois, +5000 cheveux* ! Ce soin booster capillaire agit au cœur du cuir chevelu pour une action ciblée 2-en-1 : chute des cheveux freinée, et densité boostée. Les cheveux sont plus nombreux et plus forts , la masse capillaire est plus dense. Une texture non grasse et invisible sur les cheveux, à l’application facile.", 50.00, '/assets/img/products/booster_capillaire_anti_chute.PNG', 1),
('Shampooing Fortifiant Anti-Chute Sans Sulfate', "Enrichi en Agave Bio et en Lupin Blanc, le Shampooing Fortifiant Sans Sulfate stimule le cuir chevelu et freine la chute de cheveux. Les cheveux poussent plus forts, plus denses et sont pleins de vitalité. Type de cheveux : Cheveux fatigués, dévitalisés. Texture : Gel translucide. Bénéfices : Freine la chute. Spécialement formulé sans sulfate* et sans silicone pour les cheveux dévitalisés à fatigués, le shampooing anti-chute lave tout en douceur et stimule le cuir chevelu.", 8.00, '/assets/img/products/shampooing_fortifiant_anti_chute_sans_sulfate.PNG', 1),
('Lattafa Give Me Gourmand Choco Overdose', "L'eau de parfum mixte Give Me Gourmand Choco Overdose de Lattafa a été conçue pour conquérir vos coeurs dès le premier coup d'oeiil, dès la première inspiration. En effet, cette composition olfactive sucrée se dissimule dans un flacon ludique qui reproduit la forme d'un cupcake au chocolat. Une composition olfactive sucrée et sophistiquée qui possède une fragrance qui évolue au fil du temps à porter en soirée ou pour des occasions spéciales.", 40.80, '/assets/img/products/lattafa_give_me_gourmand_choco_overdose.png', 7),
('Lattafa Give Me Gourmand Cookie Crave', "Amateurs des gâteaux au chocolat, ceci va vous plaire. L'eau de parfum mixte Give Me Gourmand Choco Overdose de Lattafa a été conçue pour conquérir vos coeurs dès le premier coup d'oeil, dès la première inspiration. En effet, cette composition olfactive sucrée se dissimule dans un flacon ludique qui reproduit la forme d'un cupcake au chocolat. Ce Parfum possède une composition olfactive sucrée et sophistiquée, une fragrance qui évolue au fil du temps, à porter en soirée ou pour des occasions spéciales.", 40.80, '/assets/img/products/lattafa_give_me_gourmand_cookie_crave.png', 7),
('Lattafa Give Me Gourmand Whipped Pleasure', "Seriez-vous d'accord pour dire que le parfum des cupcakes sortant du four et décors de chantilly est tout juste irrésistible ? Dans ce cas, vous ne pourrez que succomber à l'eau de parfum mixte Give Me Gourmand Whipped Pleasure de Lattafa. Elle vous séduira non seulement par son parfum sucré, mais aussi par le design ludique de son flacon qui reproduit la forme du célèbre petit gâteau. Une composition olfactive gourmande présentée en 2025 et créée par la parfumeuse Nisrine Bouazzaoui Grilli.", 40.80, '/assets/img/products/lattafa_give_me_gourmand_whipped_pleasure.png', 7),
('Filorga Time-Filler Eyes 5XP', "La peau sensible du contour des yeux est probablement la plus sujette aux signes visibles de vieillissement. La crème contour des yeux Filorga Time-Filler Eyes 5 XP Correction Eye Cream agit directement sur les trois signes visibles du vieillissement de la peau : elle lisse les rides, elle agit contre le relâchement des paupières supérieures et elle réduit les cernes. Sa composition inspirée des techniques de la médecine esthétique aide à lisser les rides et les ridules du contour des yeux alors que son complexe liftant agit contre le relâchement de la peau des paupières. De plus, la matrikine stimulante associée à la provitamine B5 renforce visiblement les cils. Prenez soin du contour de vos yeux et redonnez un aspect visiblement rajeuni à votre peau.", 39.95, '/assets/img/products/filorga_time_filler_eyes_5xp.png', 0),
('Mario Badescu Super Collagen Mask', "Offrez à votre peau un réconfort nourrissant tout en la stimulant en 20 minutes seulement. Le masque liftant éclaircissant Mario Badescu Super Collagen Mask enrichi en collagène et en kaolin convient parfaitement aux peaux mixtes, sensibles et sèches. Grâce à sa composition, il élimine les premiers signes de vieillissement, rend votre peau plus douce et favorise sa jeunesse. Essayez un produit de renom qui a été l'un des premiers en son genre à être lancé sur le marché.", 23.00, '/assets/img/products/mario_badescu_super_collagen_mask.png', 0),
('Mario Badescu Cleansing Oil', "Que diriez-vous de nourrir et d'hydrater votre peau en profondeur pendant le processus de démaquillage ? L'huile démaquillante purifiante Mario Badescu Cleansing Oil est un excellent nettoyant qui ne vous expose pas au risque de sécheresse. Elle peut même prendre en charge le maquillage waterproof et laisser votre peau merveilleusement fraîche et apaisée.", 22.00, '/assets/img/products/mario_badescu_cleansing_oil.png', 0);
